### ISSUE TITLE
AttributeError when trying to retrieve perf data from WAS

### ISSUE THREAD

**Issue by castorsenior** [dvarounis/perfservmon#12]
Hello Dimos,

When I run this command :
./perfservmon.py -C HP-ProBook-G5Node01Cell retrieve -N localhost -P 9443 -H https

I receive this message :
Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/perfservmon.py", line 804, in <module>
    parseperfxml(path=startingpath, cellname=arguments.CellName)
  File "/usr/lib/nagios/plugins/perfservmon.py", line 466, in parseperfxml
    with shelve.open(shelvefilename, flag='c') as pfile:
AttributeError: DbfilenameShelf instance has no attribute '__exit__'

After I run this command :
./perfservmon.py -C HP-ProBook-G5Node01Cell show -n HP-ProBook-G5Node01 -s server1 -M WebContainer -c 90 -w 70

and the machine answers :
UNKNOWN - Error opening cached metrics file

Could you help me to find what's wrong ?
Thank you very much,
with best regards,
Mikhael

**Comment by castorsenior** [comment]
I'm working with the 60-days developer trial version of WAS. 
Here is, in attachment, my XML. Thanks !
[perfservlet.txt](https://github.com/dvarounis/perfservmon/files/2611476/perfservlet.txt)

**Comment by castorsenior** [comment]
$ python --version
Python 2.7.15rc1

**Comment by castorsenior** [comment]
Hello,
In my context, everything works well with the previous release (Aug 9, 2018), which does not implement _context manager_ `shelve`.
Thank you Dimos for your job with Perfservmon :-)
